name: hello_flutter
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.8
  intl: ^0.17.0
  provider: ^6.0.3
  http: ^0.13.4
  cupertino_icons: ^1.0.2
  path: ^1.8.2
  sticky_headers: ^0.3.0+2
  open_file: ^3.0.3
  path_provider: ^2.0.15
  # native_pdf_renderer: ^4.0.1
  # pdfx: ^1.0.0

 

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0




flutter:


  uses-material-design: true


  